
output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Digital Child Health (TEST) (DCH) | FHIR&reg;
# this appears on the top navigation bar next to the home button

site_title: Digital Child Health (TEST) (DCH) 
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: NHS Digital
# this appears in the footer

#github_editme_path: /edit/develop/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

#disqus: true
#disqus_shortname: disqus_shortname

#gitter: true
#gitter_room: gitter_account/gitter_room

#tiny_letter: true
#tiny_letter_username: tiny_letter_username

#twitter: true
#twitter_username: twitter_username
#twitter_site_hashtags: twitter_site_hashtags

fhir_profile_baseurl: https://fhir.nhs.uk/StructureDefinition/
fhir_profile_ext:

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4005
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .vscode/
  - .idea/
  - .gitignore
# these are the files and directories that jekyll will exclude from the build

feedback_email: interoperabilityteam@nhs.net
# used as a contact email for the Feedback link in the top navigation bar

feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: overview_sidebar

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
      sidebar: overview_sidebar

# these are defaults used for the frontmatter for these file types

sidebars:
- overview_sidebar
- overview_sidebar
- designprinciples_sidebar
- accessrecord_sidebar
- appointments_sidebar
- tasks_sidebar

description: "This implementation guide supports the publishing of Digital Child Health (TEST) (DCH) event messages held across settings through the use of nationally defined messaging components."
# the description is used in the feed.xml file

sitemap: true

# needed for sitemap.xml file only
url: https://nhsconnect.github.io/Digital-Child-Health-STU3

repository: nhsconnect/Digital-Child-Health-STU3

gist:
  noscript: false

site:
  fhirprofiles:
    patient: "[Care Connect Patient](http://www.interopen.org/candidate-profiles/care-connect/CareConnect-Patient-1.html)"

gems:
   - jekyll-github-metadata
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-seo-tag
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-gist
